function matlap_code

clc; clear;

port = "COM16";
baud = 9600;

s = serialport(port, baud);
configureTerminator(s,"LF");
flush(s);
pause(2);

fig = uifigure('Name','5-DOF Robot Arm Controller',...
    'Color',[0.1 0.1 0.1],...
    'Position',[400 150 520 620]);

sliders = gobjects(6,1);

for i = 1:6
    uilabel(fig,...
        'Text',"Servo " + i,...
        'FontColor','w',...
        'FontSize',12,...
        'Position',[30 560-(i*70) 70 22]);

    sliders(i) = uislider(fig,...
        'Limits',[0 180],...
        'Value',90,...
        'Position',[120 570-(i*70) 350 3],...
        'ValueChangingFcn',@(src,event) liveMove(s,i,event.Value));
end

uibutton(fig,'Text','SAVE POSE',...
    'FontSize',14,...
    'BackgroundColor',[0.2 0.6 0.2],...
    'FontColor','w',...
    'Position',[40 40 130 50],...
    'ButtonPushedFcn',@(btn,event) writeline(s,"SAVE"));

uibutton(fig,'Text','PLAY',...
    'FontSize',14,...
    'BackgroundColor',[0.2 0.4 0.8],...
    'FontColor','w',...
    'Position',[195 40 130 50],...
    'ButtonPushedFcn',@(btn,event) writeline(s,"PLAY"));

uibutton(fig,'Text','RESET',...
    'FontSize',14,...
    'BackgroundColor',[0.7 0.2 0.2],...
    'FontColor','w',...
    'Position',[350 40 130 50],...
    'ButtonPushedFcn',@(btn,event) resetSystem(s,sliders));

fig.CloseRequestFcn = @(src,event) closeGUI(s,fig);

end

function liveMove(s,servo,val)
    cmd = sprintf("M,%d,%d\n",servo,round(val));
    write(s,cmd,"string");
    drawnow limitrate;
end

function resetSystem(s,sliders)
    writeline(s,"RESET");
    pause(0.1);
    for i = 1:length(sliders)
        sliders(i).Value = 90;
    end
end

function closeGUI(s,fig)
    clear s;
    delete(fig);
end
